config/routes.rb
UvAcoursesApp::Application.routes.draw do
  resources :take_courses

  resources :line_courses

  resources :carts

  resources :courses

  root 'courses#index'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	# The :dependent => :destroy part indicates that the existence of line items is dependent on the existence of the cart.
	has_many :line_course, :dependent => :destroy
	has_many :take_course, :dependent => :destroy
	
	#checks whether our list of items already includes the course we’re adding; if it does, it bumps the quantity, and if it doesn’t, it builds a new 			LineCourse
	def shopping_course(course_id)
		current_course = line_course.find_by_course_id(course_id)
		if current_course
    		current_course.quantity += 1
		else
    		current_course = line_course.build(:course_id => course_id)
		end
  		current_course
	end
	
	def taking_course(course_id)
		current_course = take_course.find_by_course_id(course_id)
		if current_course
    		
		else
    		current_course = take_course.build(:course_id => course_id)
		end
  		current_course
	end
	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  		@carts = Cart.all
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<!DOCTYPE html>

<h1><div class="cart_title">Courses you are shopping</div></h1>

<table>
	<% if cart.line_course %>
	
  <%= render(@cart.line_course) %>
	<% end %>
	<tr>
		
  </tr>
</table>
<br>
<div style="float:left;">
	<%= button_to 'Empty cart', cart, :method => :delete,
	:confirm => 'Are you sure?' %>
</div>
<div style="float:left;">    
	<%= button_to "Back to Browse", courses_path, :id => "open-contacts-dialog-btn", 
	:class => "inbox-sf-add-btn tip", :method => :get %>
</div>

app/views/carts/_taking.html.erb
<!DOCTYPE html>

<h1><div class="cart_title">Courses you are taking</div></h1>

<table>
	<tr>
	
		
  		<%= render(@cart.take_course) %>
  		
  </tr>
  
</table>

<br>

<div style="float:left;">    
	<%= button_to "Back to Browse", courses_path, :id => "open-contacts-dialog-btn", 
	:class => "inbox-sf-add-btn tip", :method => :get %>
</div>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!--<!DOCTYPE html>

<div class="cart_title">Your Cart</div>

<table>
  <%= render(@cart.line_course) %>
	
	<tr class="total_line">
		<td colspan="2">Total</td>
  </tr>

</table>

<%= button_to 'Empty cart', @cart, :method => :delete,
    :confirm => 'Are you sure?' %>-->
    
    <%= render @cart %>